# --- PACKAGES FOR ALL SYSTEMS (WSL + NATIVE) ---
common_packages:
  # Core
  - base-devel
  - git
  - ansible
  - chezmoi
  - fish
  - starship
  - neovim
  - direnv
  - bat
  - eza
  - fzf
  - zoxide
  - ripgrep
  - btop
  - fastfetch
  - 7zip
  - unarchiver
  - wget
  - curl
  - man-db
  - lazygit
  
  # Dev Toolchain
  - cmake
  - extra-cmake-modules
  - ninja
  - clang
  - gdb
  - doxygen
  
  # Python basics
  - python-pip
  - python-setuptools

# --- AUR PACKAGES (CLI ONLY) ---
common_aur_pkgs:
  - github-desktop-bin   # Works in WSLg
  - sublime-merge        # Works in WSLg
  - localsend-bin        # Works in WSLg
