# --- PACKAGES FOR ALL SYSTEMS (WSL + NATIVE) ---
common_packages:
  # Core
  - base-devel
  - git
  - ansible
  - chezmoi
  - fish
  - kitty
  - alacritty
  - starship
  - neovim
  - direnv
  - bat
  - eza
  - fzf
  - zoxide
  - ripgrep
  - btop
  - fastfetch
  - 7zip
  - unarchiver
  - wget
  - curl
  - man-db
  - lazygit
  - dunst
  - inetutils
  - keychain
  
  # Fonts
  - ttf-jetbrains-mono-nerd

  # Dev Toolchain
  - cmake
  - extra-cmake-modules
  - ninja
  - clang
  - gdb
  - doxygen
  - bun
  - pnpm
  - nodejs
  - gmp
  - libffi
  - rustup
  - ollama
  - element-desktop
  
  # Python basics
  - python-pip
  - python-setuptools

  # Graphics
  - mesa
  - mesa-utils
  - vulkan-icd-loader
  - vulkan-swrast
  - libva

  # Video player
  - haruna
  - mpv

# --- AUR PACKAGES (CLI ONLY) ---
common_aur_pkgs:
  - github-desktop-bin   # Works in WSLg
  - sublime-merge        # Works in WSLg
  - localsend-bin        # Works in WSLg
  - elan-bin
  - freetube-bin
  - visual-studio-code-bin

dev_structure:
  - dev/docs
  - dev/bin
  - dev/scripts
  - dev/src/github.com
  - dev/src/forgejo.wyattau.com

# GHQ CONFIG
ghq_root: "~/dev/src"