hardware_packages:
  - nvidia-open-dkms
  - nvidia-utils
  - nvidia-settings
  - libva-nvidia-driver
  - vulkan-tools
  - sof-firmware
  - alsa-tools
  - scx-scheds
  - libfprint
  - fprintd
  - python-hidapi
  - python-setuptools
  # Virtualization
  - qemu-full
  - virt-manager
  - virt-viewer
  - dnsmasq
  - vde2
  - openbsd-netcat
  - libguestfs

aur_pkgs:
  - envycontrol
  - kwin-scripts-polonium-git
  - winapps-git
  - mcontrolcenter-git
  - msi-ec-dkms-git
  - scx-git
  - whitesur-icon-theme-git
  - moe-theme-git          # <-- Fixed Typo
  - openrgb-git
  - pika-backup
  - freetube-bin
  - ksshaskpass
  - msi-perkeyrgb
  - ksshaskpass

host_services:
  - msi-speaker-fix
  - libvirtd

masked_services:
  - packagekit.service
