# --- MSI SPECIFIC DRIVERS ---
host_packages:
  - nvidia-open-dkms
  - nvidia-utils
  - nvidia-settings
  - libva-nvidia-driver
  - vulkan-tools
  - sof-firmware
  - alsa-tools
  - scx-scheds
  - libfprint
  - fprintd
  - python-hidapi
  - python-setuptools

host_aur_pkgs:
  - envycontrol
  - mcontrolcenter-git
  - msi-ec-dkms-git
  - scx-git
  - whitesur-icon-theme-git
  - moe-theme-git
  - openrgb-git
  - msi-perkeyrgb

host_services:
  - msi-speaker-fix
  - libvirtd

masked_services:
  - packagekit.service